
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module pocket_game(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// I2C for Audio and Video-In //////////
	output		          		FPGA_I2C_SCLK,
	inout 		          		FPGA_I2C_SDAT,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// Video-In //////////
	input 		          		TD_CLK27,
	input 		     [7:0]		TD_DATA,
	input 		          		TD_HS,
	output		          		TD_RESET_N,
	input 		          		TD_VS,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
// pocket_game.v
// Bu, tüm oyun modüllerini içeren en üst seviye modüldür.
/*module pocket_game (
    // Global Saatler ve Reset
    input wire CLK_50MHZ,         // FPGA'den gelen ana saat (örn: 50MHz)
    input wire RESET_N,           // Aktif düşük global reset

    // Anahtar Girişleri (FPGA üzerindeki switch'ler)
    input wire SW0_GAME_MODE,     // Oyun modu seçimi (0: 2P, 1: 1P vs CPU)
    input wire SW1_CLK_SELECT,    // Oyun mantığı saat seçimi (Proje tanımına göre)

    // Oyuncu 1 Buton Girişleri (FPGA üzerindeki butonlar veya harici)
    input wire P1_BTN_LEFT,
    input wire P1_BTN_RIGHT,
    input wire P1_BTN_ATTACK,
    input wire P1_BTN_CONFIRM,

    // Oyuncu 2 Buton Girişleri (Harici keypad)
    input wire P2_BTN_LEFT,
    input wire P2_BTN_RIGHT,
    input wire P2_BTN_ATTACK,

    // VGA Çıkışları (Monitöre)
    output wire VGA_HS,           // Yatay senkronizasyon
    output wire VGA_VS,           // Dikey senkronizasyon
    output wire [7:0] VGA_RGB,    // RRRGGGBB renk çıkışı

    // LED Çıkışları
    output wire [2:0] LED_P1_HEALTH,
    output wire [2:0] LED_P2_HEALTH,
    output wire LED_GAME_OVER_BLINK, // Tüm LED'lerin yanıp sönmesi için genel sinyal (led_driver içinde yönetilecek)

    // 7-Segment Gösterge Çıkışları (Sürücüye gidecek sinyaller)
    // Gerçek 7-segment anot/katot ve segment sinyalleri seven_segment_driver.v içinde üretilecek.
    // Buradan seven_segment_driver'a bilgi aktarılacak.
    output wire [6:0] SEG7_DATA_0, // Örnek: 4 haneli gösterge için veri hatları
    output wire [6:0] SEG7_DATA_1,
    output wire [6:0] SEG7_DATA_2,
    output wire [6:0] SEG7_DATA_3,
    output wire [3:0] SEG7_AN     // Örnek: 4 haneli gösterge için anot/katot seçimi
);
*/
    // Sinyal Tanımlamaları
    wire clk_game_logic; // Oyun mantığı için 60Hz saat
    wire clk_vga_pixel;  // VGA piksel saati (örn: 25MHz)
    wire reset_sync;     // Senkronize edilmiş reset

    // Input Handler'dan gelen işlenmiş girişler
    wire p1_move_left_debounced;
    wire p1_move_right_debounced;
    wire p1_attack_debounced;
    wire p1_confirm_debounced;
    wire p2_move_left_debounced;
    wire p2_move_right_debounced;
    wire p2_attack_debounced;
    wire game_mode_selected; // input_handler'dan gelen seçilmiş mod

    // CPU Bot'tan gelen Oyuncu 2 hareketleri (1P modunda)
    wire p2_cpu_move_left;
    wire p2_cpu_move_right;
    wire p2_cpu_attack;

    // Player FSM'lerden gelen bilgiler
    wire [9:0] p1_x_pos, p2_x_pos;
    wire [2:0] p1_current_state, p2_current_state;
    wire p1_is_attacking_active, p2_is_attacking_active; // Saldırının aktif olduğu an
    wire p1_facing_right, p2_facing_right;
    // Vuruş kutusu/hasar kutusu bilgileri (player_fsm'lerden game_logic_fsm'e)
    // Bu yapı, oyunun karmaşıklığına göre detaylandırılmalıdır.
    // Örnek olarak, aktif vuruş kutusunun başlangıç ve bitiş X koordinatları:
    wire [9:0] p1_hitbox_x1, p1_hitbox_x2;
    wire [9:0] p2_hitbox_x1, p2_hitbox_x2;
    // Hasar kutusu (genellikle oyuncu sprite'ı ile aynı)
    wire [9:0] p1_hurtbox_x1, p1_hurtbox_x2;
    wire [9:0] p2_hurtbox_x1, p2_hurtbox_x2;


    // Game Logic FSM'den gelen genel oyun durumu bilgileri
    wire [1:0] game_phase;          // 00:MENU, 01:COUNTDOWN, 10:GAMEPLAY, 11:GAMEOVER
    wire [2:0] countdown_value;     // Geri sayım için (3,2,1,0)
    wire [6:0] game_seconds_elapsed;
    wire [1:0] winner_info;         // 00:None, 01:P1, 10:P2, 11:Draw
    wire [2:0] p1_hp_current, p2_hp_current;
    wire [2:0] p1_bp_current, p2_bp_current;
    wire all_leds_blink_cmd; // game_logic_fsm'den led_driver'a

    // VGA Renderer'a gidecek renk bilgisi
    wire [7:0] vga_color_render_out;
    // VGA Driver'dan gelen koordinatlar
    wire [9:0] vga_current_x;
    wire [9:0] vga_current_y;
    wire vga_pixel_enable; // VGA'nın aktif çizim alanında olduğunu gösterir


    //-------------------------------------------------------------------------
    // Modül Örneklemeleri (Instantiations)
    //-------------------------------------------------------------------------

    // 1. Saat Yönetimi ve Reset Senkronizasyonu
    // Not: clock_manager_with_divider.v, clock_divider_functional.v'yi içinde barındırabilir.
    // SW1_CLK_SELECT ile 60Hz veya KEY ile saat seçimi burada yönetilir.
    // Basitlik adına, doğrudan 60Hz ve 25MHz saatlerin üretildiğini varsayalım.
    // Gerçek bir clock_manager modülü, CLK_50MHZ'den bu saatleri üretmelidir.
    // assign clk_game_logic = ... (clock_manager'dan gelecek)
    // assign clk_vga_pixel  = ... (clock_manager'dan gelecek)
    // assign reset_sync     = ~RESET_N; // Aktif yüksek reset için basit senkronizasyon gerekebilir.

    // Örnek: Doğrudan atama (gerçekte clock_manager kullanılmalı)
    clock_manager_with_divider clk_manager_inst (
        .clk_in_50mhz(CLK_50MHZ),
        .reset_in(RESET_N), // clock_manager reset alabilir
        .clk_select_key_60hz(SW1_CLK_SELECT), // Proje tanımına göre
        // .external_key_clk_in(KEY_INPUT_FOR_GAME_LOGIC), // Eğer harici bir tuşla saat sürülüyorsa
        .clk_out_game_logic(clk_game_logic),
        .clk_out_vga_pixel(clk_vga_pixel),
        .reset_out_sync(reset_sync) // Senkronize edilmiş reset çıkışı
    );

    // 2. Giriş Yöneticisi (Input Handler)
    // Sektirme önleme (debouncing) burada yapılmalıdır.
    input_handler input_handler_inst (
        .clk(clk_game_logic), // Debouncer için saat
        .reset(reset_sync),
        .p1_btn_left_raw(P1_BTN_LEFT),
        .p1_btn_right_raw(P1_BTN_RIGHT),
        .p1_btn_attack_raw(P1_BTN_ATTACK),
        .p1_btn_confirm_raw(P1_BTN_CONFIRM),
        .p2_btn_left_raw(P2_BTN_LEFT),
        .p2_btn_right_raw(P2_BTN_RIGHT),
        .p2_btn_attack_raw(P2_BTN_ATTACK),
        .sw_game_mode_raw(SW0_GAME_MODE),

        .p1_move_left_out(p1_move_left_debounced),
        .p1_move_right_out(p1_move_right_debounced),
        .p1_attack_out(p1_attack_debounced),
        .p1_confirm_out(p1_confirm_debounced),
        .p2_move_left_out(p2_move_left_debounced),
        .p2_move_right_out(p2_move_right_debounced),
        .p2_attack_out(p2_attack_debounced),
        .game_mode_out(game_mode_selected)
    );

    // 3. CPU Bot (Eğer 1P mod seçiliyse aktif olur)
    cpu_bot cpu_bot_inst (
        .clk_game_logic(clk_game_logic),
        .reset(reset_sync),
        .enable_bot(game_mode_selected), // Sadece 1P modunda aktif
        .p1_x_pos_in(p1_x_pos),          // Rakip (P1) konumu
        .p2_x_pos_in(p2_x_pos),          // Kendi (P2/CPU) konumu
        // .game_state_in(...)        // Gerekirse daha fazla oyun durumu bilgisi

        .cpu_move_left_out(p2_cpu_move_left),
        .cpu_move_right_out(p2_cpu_move_right),
        .cpu_attack_out(p2_cpu_attack)
    );

    // Oyuncu 2 için nihai hareketler (CPU veya insan)
    wire p2_final_move_left_input  = game_mode_selected ? p2_cpu_move_left  : p2_move_left_debounced;
    wire p2_final_move_right_input = game_mode_selected ? p2_cpu_move_right : p2_move_right_debounced;
    wire p2_final_attack_input     = game_mode_selected ? p2_cpu_attack     : p2_attack_debounced;

    // 4. Oyuncu 1 FSM
    player_fsm player1_fsm_inst (
        .clk_game_logic(clk_game_logic),
        .reset(reset_sync),
        .move_left_in(p1_move_left_debounced),
        .move_right_in(p1_move_right_debounced),
        .attack_in(p1_attack_debounced),
        .initial_x(P1_INITIAL_X_PARAM), // Parametre olarak tanımlanabilir
        .initial_facing_right(1'b1),
        .opponent_x_pos(p2_x_pos),
        .opponent_is_attacking(p2_is_attacking_active),
        .opponent_hitbox_x1(p2_hitbox_x1),
        .opponent_hitbox_x2(p2_hitbox_x2),
        .got_hit_trigger(p1_got_hit_trigger_from_game_logic), // game_logic_fsm'den
        .got_blocked_trigger(p1_got_blocked_trigger_from_game_logic), // game_logic_fsm'den
        .current_hp_in(p1_hp_current), // game_logic_fsm'den
        .current_bp_in(p1_bp_current), // game_logic_fsm'den

        .player_x_pos_out(p1_x_pos),
        .player_current_state_out(p1_current_state),
        .player_is_attacking_active_out(p1_is_attacking_active),
        .player_facing_right_out(p1_facing_right),
        .player_hitbox_x1_out(p1_hitbox_x1),
        .player_hitbox_x2_out(p1_hitbox_x2),
        .player_hurtbox_x1_out(p1_hurtbox_x1), // Genellikle (p1_x_pos)
        .player_hurtbox_x2_out(p1_hurtbox_x2)  // Genellikle (p1_x_pos + PLAYER_SPRITE_W)
    );
    localparam P1_INITIAL_X_PARAM = 100;
    localparam P2_INITIAL_X_PARAM = 640 - 100 - 64; // PLAYER_SPRITE_W = 64

    // 5. Oyuncu 2 FSM
    player_fsm player2_fsm_inst (
        .clk_game_logic(clk_game_logic),
        .reset(reset_sync),
        .move_left_in(p2_final_move_left_input),
        .move_right_in(p2_final_move_right_input),
        .attack_in(p2_final_attack_input),
        .initial_x(P2_INITIAL_X_PARAM),
        .initial_facing_right(1'b0),
        .opponent_x_pos(p1_x_pos),
        .opponent_is_attacking(p1_is_attacking_active),
        .opponent_hitbox_x1(p1_hitbox_x1),
        .opponent_hitbox_x2(p1_hitbox_x2),
        .got_hit_trigger(p2_got_hit_trigger_from_game_logic),
        .got_blocked_trigger(p2_got_blocked_trigger_from_game_logic),
        .current_hp_in(p2_hp_current),
        .current_bp_in(p2_bp_current),

        .player_x_pos_out(p2_x_pos),
        .player_current_state_out(p2_current_state),
        .player_is_attacking_active_out(p2_is_attacking_active),
        .player_facing_right_out(p2_facing_right),
        .player_hitbox_x1_out(p2_hitbox_x1),
        .player_hitbox_x2_out(p2_hitbox_x2),
        .player_hurtbox_x1_out(p2_hurtbox_x1),
        .player_hurtbox_x2_out(p2_hurtbox_x2)
    );

    // 6. Oyun Mantığı FSM (Ana Oyun Yöneticisi)
    // Bu modül, vuruş tespiti, skor tutma, oyun aşamalarını yönetme gibi işlemleri yapar.
    wire p1_got_hit_trigger_from_game_logic;
    wire p1_got_blocked_trigger_from_game_logic;
    wire p2_got_hit_trigger_from_game_logic;
    wire p2_got_blocked_trigger_from_game_logic;

    game_logic_fsm game_logic_fsm_inst (
        .clk_game_logic(clk_game_logic),
        .reset(reset_sync),
        .p1_confirm_in(p1_confirm_debounced),
        .selected_mode_in(game_mode_selected),

        .p1_x_in(p1_x_pos),
        .p1_state_in(p1_current_state),
        .p1_is_attacking_active_in(p1_is_attacking_active),
        .p1_hitbox_x1_in(p1_hitbox_x1),
        .p1_hitbox_x2_in(p1_hitbox_x2),
        .p1_hurtbox_x1_in(p1_hurtbox_x1),
        .p1_hurtbox_x2_in(p1_hurtbox_x2),
        .p1_is_moving_backward_in(p1_current_state == 3'b010), // P_STATE_MOVE_B

        .p2_x_in(p2_x_pos),
        .p2_state_in(p2_current_state),
        .p2_is_attacking_active_in(p2_is_attacking_active),
        .p2_hitbox_x1_in(p2_hitbox_x1),
        .p2_hitbox_x2_in(p2_hitbox_x2),
        .p2_hurtbox_x1_in(p2_hurtbox_x1),
        .p2_hurtbox_x2_in(p2_hurtbox_x2),
        .p2_is_moving_backward_in(p2_current_state == 3'b010), // P_STATE_MOVE_B

        .game_phase_out(game_phase),
        .countdown_value_out(countdown_value),
        .game_seconds_elapsed_out(game_seconds_elapsed),
        .winner_info_out(winner_info),
        .p1_hp_out(p1_hp_current),
        .p1_bp_out(p1_bp_current),
        .p2_hp_out(p2_hp_current),
        .p2_bp_out(p2_bp_current),
        .all_leds_blink_cmd_out(all_leds_blink_cmd),

        .p1_hit_confirm_out(p1_got_hit_trigger_from_game_logic),
        .p1_block_confirm_out(p1_got_blocked_trigger_from_game_logic),
        .p2_hit_confirm_out(p2_got_hit_trigger_from_game_logic),
        .p2_block_confirm_out(p2_got_blocked_trigger_from_game_logic)
    );

    // 7. VGA Sürücüsü (Standart VGA Kontrolcüsü)
    // Bu, HSYNC, VSYNC ve piksel koordinatlarını (vga_current_x, vga_current_y) üretir.
    // Genellikle hazır bir IP veya modül olarak kullanılır.
    vga_driver vga_driver_inst (
        .pixel_clk(clk_vga_pixel),
        .reset(reset_sync),
        .h_sync_out(VGA_HS),
        .v_sync_out(VGA_VS),
        .video_on_out(vga_pixel_enable), // Aktif çizim alanı
        .pixel_x_out(vga_current_x),
        .pixel_y_out(vga_current_y)
    );

    // 8. VGA Renk Oluşturucu (Renderer)
    // Bu modül, vga_driver'dan gelen koordinatlara ve oyun durumuna göre piksel renklerini belirler.
    vga_renderer vga_renderer_inst (
        .clk_pixel(clk_vga_pixel), // Bu modülün iç mantığı kombinasyonel olabilir veya piksel saatine göre kaydedilebilir.
        .reset(reset_sync),
        .vga_x_in(vga_current_x),
        .vga_y_in(vga_current_y),
        .vga_video_enable_in(vga_pixel_enable),

        .game_phase_in(game_phase),
        .countdown_value_in(countdown_value),
        .winner_info_in(winner_info),
        .game_seconds_in(game_seconds_elapsed),
        .selected_mode_in(game_mode_selected), // Menüde 1P/2P göstermek için

        .p1_x_in(p1_x_pos),
        .p1_hp_in(p1_hp_current),
        .p1_bp_in(p1_bp_current),
        .p1_state_in(p1_current_state),
        .p1_facing_right_in(p1_facing_right),

        .p2_x_in(p2_x_pos),
        .p2_hp_in(p2_hp_current),
        .p2_bp_in(p2_bp_current),
        .p2_state_in(p2_current_state),
        .p2_facing_right_in(p2_facing_right),

        .vga_rgb_out(vga_color_render_out)
    );
    assign VGA_RGB = vga_pixel_enable ? vga_color_render_out : 8'b0; // Blanking sırasında siyah

    // 9. LED Sürücüsü
    led_driver led_driver_inst (
        .clk(clk_game_logic), // Yanıp sönme için saat
        .reset(reset_sync),
        .p1_health_in(p1_hp_current),
        .p2_health_in(p2_hp_current),
        .blink_enable_in(all_leds_blink_cmd), // game_logic_fsm'den
        .game_phase_in(game_phase), // Menüde LED'leri kapatmak için

        .p1_health_led_out(LED_P1_HEALTH),
        .p2_health_led_out(LED_P2_HEALTH),
        .all_leds_physical_out(LED_GAME_OVER_BLINK) // Bu, tüm LED'leri süren tek bir sinyal olabilir veya ayrı ayrı yönetilebilir.
    );

    // 10. 7-Segment Gösterge Sürücüsü
    seven_segment_driver seven_segment_driver_inst (
        .clk(clk_game_logic), // Multiplexing için saat
        .reset(reset_sync),
        .game_phase_in(game_phase),
        .selected_mode_in(game_mode_selected), // Menüde 1P/2P göstermek için
        .winner_info_in(winner_info),
        .game_time_in(game_seconds_elapsed),

        // Fiziksel 7-segment çıkışları
        .seg_data_0_out(SEG7_DATA_0),
        .seg_data_1_out(SEG7_DATA_1),
        .seg_data_2_out(SEG7_DATA_2),
        .seg_data_3_out(SEG7_DATA_3),
        .seg_an_out(SEG7_AN)
    );

endmodule




//=======================================================
//  Structural coding
//=======================================================



endmodule
